// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntelliSwingService.proto

#include "IntelliSwingService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace IntelliSwing {
constexpr DeviceInfo::DeviceInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : devicever_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , fpgaver_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , softwarever_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , serialnumber_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct DeviceInfoDefaultTypeInternal {
  constexpr DeviceInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DeviceInfoDefaultTypeInternal() {}
  union {
    DeviceInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DeviceInfoDefaultTypeInternal _DeviceInfo_default_instance_;
constexpr DiviceStatus::DiviceStatus(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sensorstate_()
  , systemstate_(nullptr)
  , devicetemperature_(0)
  , batteryinfo_(0){}
struct DiviceStatusDefaultTypeInternal {
  constexpr DiviceStatusDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DiviceStatusDefaultTypeInternal() {}
  union {
    DiviceStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DiviceStatusDefaultTypeInternal _DiviceStatus_default_instance_;
constexpr LogRequest::LogRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : systemrange_(0)
  , processinglogrange_(0){}
struct LogRequestDefaultTypeInternal {
  constexpr LogRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~LogRequestDefaultTypeInternal() {}
  union {
    LogRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT LogRequestDefaultTypeInternal _LogRequest_default_instance_;
constexpr LogMessage::LogMessage(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : systemlog_()
  , processinglog_(){}
struct LogMessageDefaultTypeInternal {
  constexpr LogMessageDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~LogMessageDefaultTypeInternal() {}
  union {
    LogMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT LogMessageDefaultTypeInternal _LogMessage_default_instance_;
constexpr SensorStatistics::SensorStatistics(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : shot_count_(0){}
struct SensorStatisticsDefaultTypeInternal {
  constexpr SensorStatisticsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SensorStatisticsDefaultTypeInternal() {}
  union {
    SensorStatistics _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SensorStatisticsDefaultTypeInternal _SensorStatistics_default_instance_;
constexpr SiteCalibrationResult::SiteCalibrationResult(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : state_(nullptr){}
struct SiteCalibrationResultDefaultTypeInternal {
  constexpr SiteCalibrationResultDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SiteCalibrationResultDefaultTypeInternal() {}
  union {
    SiteCalibrationResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SiteCalibrationResultDefaultTypeInternal _SiteCalibrationResult_default_instance_;
constexpr Firmware::Firmware(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sensorfirmware_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , fpgafirmware_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct FirmwareDefaultTypeInternal {
  constexpr FirmwareDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FirmwareDefaultTypeInternal() {}
  union {
    Firmware _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FirmwareDefaultTypeInternal _Firmware_default_instance_;
constexpr UpdateFirmwareResult::UpdateFirmwareResult(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : fpgastate_(nullptr)
  , sensorsw_(nullptr){}
struct UpdateFirmwareResultDefaultTypeInternal {
  constexpr UpdateFirmwareResultDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~UpdateFirmwareResultDefaultTypeInternal() {}
  union {
    UpdateFirmwareResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT UpdateFirmwareResultDefaultTypeInternal _UpdateFirmwareResult_default_instance_;
}  // namespace IntelliSwing
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_IntelliSwingService_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_IntelliSwingService_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_IntelliSwingService_2eproto = nullptr;

const uint32_t TableStruct_IntelliSwingService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DeviceInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DeviceInfo, devicever_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DeviceInfo, fpgaver_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DeviceInfo, softwarever_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DeviceInfo, serialnumber_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DiviceStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DiviceStatus, sensorstate_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DiviceStatus, systemstate_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DiviceStatus, devicetemperature_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::DiviceStatus, batteryinfo_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::LogRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::LogRequest, systemrange_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::LogRequest, processinglogrange_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::LogMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::LogMessage, systemlog_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::LogMessage, processinglog_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::SensorStatistics, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::SensorStatistics, shot_count_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::SiteCalibrationResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::SiteCalibrationResult, state_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::Firmware, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::Firmware, sensorfirmware_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::Firmware, fpgafirmware_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::UpdateFirmwareResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::UpdateFirmwareResult, fpgastate_),
  PROTOBUF_FIELD_OFFSET(::IntelliSwing::UpdateFirmwareResult, sensorsw_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::IntelliSwing::DeviceInfo)},
  { 10, -1, -1, sizeof(::IntelliSwing::DiviceStatus)},
  { 20, -1, -1, sizeof(::IntelliSwing::LogRequest)},
  { 28, -1, -1, sizeof(::IntelliSwing::LogMessage)},
  { 36, -1, -1, sizeof(::IntelliSwing::SensorStatistics)},
  { 43, -1, -1, sizeof(::IntelliSwing::SiteCalibrationResult)},
  { 50, -1, -1, sizeof(::IntelliSwing::Firmware)},
  { 58, -1, -1, sizeof(::IntelliSwing::UpdateFirmwareResult)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_DeviceInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_DiviceStatus_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_LogRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_LogMessage_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_SensorStatistics_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_SiteCalibrationResult_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_Firmware_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::IntelliSwing::_UpdateFirmwareResult_default_instance_),
};

const char descriptor_table_protodef_IntelliSwingService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031IntelliSwingService.proto\022\014IntelliSwin"
  "g\032\ntype.proto\"[\n\nDeviceInfo\022\021\n\tdeviceVer"
  "\030\001 \001(\t\022\017\n\007fpgaVer\030\002 \001(\t\022\023\n\013softwareVer\030\003"
  " \001(\t\022\024\n\014serialNumber\030\004 \001(\t\"\232\001\n\014DiviceSta"
  "tus\022,\n\013sensorState\030\001 \003(\0132\027.IntelliSwing."
  "ReturnMsg\022,\n\013systemState\030\002 \001(\0132\027.Intelli"
  "Swing.ReturnMsg\022\031\n\021deviceTemperature\030\005 \001"
  "(\002\022\023\n\013batteryInfo\030\006 \001(\002\"=\n\nLogRequest\022\023\n"
  "\013systemRange\030\001 \001(\005\022\032\n\022processingLogrange"
  "\030\002 \001(\005\"6\n\nLogMessage\022\021\n\tsystemLog\030\001 \003(\t\022"
  "\025\n\rprocessingLog\030\002 \003(\t\"&\n\020SensorStatisti"
  "cs\022\022\n\nshot_count\030\001 \001(\005\"\?\n\025SiteCalibratio"
  "nResult\022&\n\005state\030\001 \001(\0132\027.IntelliSwing.Re"
  "turnMsg\"8\n\010Firmware\022\026\n\016sensorFirmware\030\001 "
  "\001(\014\022\024\n\014fpgaFirmware\030\002 \001(\014\"m\n\024UpdateFirmw"
  "areResult\022*\n\tFpgaState\030\001 \001(\0132\027.IntelliSw"
  "ing.ReturnMsg\022)\n\010SensorSW\030\002 \001(\0132\027.Intell"
  "iSwing.ReturnMsgb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_IntelliSwingService_2eproto_deps[1] = {
  &::descriptor_table_type_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_IntelliSwingService_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IntelliSwingService_2eproto = {
  false, false, 704, descriptor_table_protodef_IntelliSwingService_2eproto, "IntelliSwingService.proto", 
  &descriptor_table_IntelliSwingService_2eproto_once, descriptor_table_IntelliSwingService_2eproto_deps, 1, 8,
  schemas, file_default_instances, TableStruct_IntelliSwingService_2eproto::offsets,
  file_level_metadata_IntelliSwingService_2eproto, file_level_enum_descriptors_IntelliSwingService_2eproto, file_level_service_descriptors_IntelliSwingService_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_IntelliSwingService_2eproto_getter() {
  return &descriptor_table_IntelliSwingService_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_IntelliSwingService_2eproto(&descriptor_table_IntelliSwingService_2eproto);
namespace IntelliSwing {

// ===================================================================

class DeviceInfo::_Internal {
 public:
};

DeviceInfo::DeviceInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.DeviceInfo)
}
DeviceInfo::DeviceInfo(const DeviceInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  devicever_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    devicever_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_devicever().empty()) {
    devicever_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_devicever(), 
      GetArenaForAllocation());
  }
  fpgaver_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    fpgaver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fpgaver().empty()) {
    fpgaver_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_fpgaver(), 
      GetArenaForAllocation());
  }
  softwarever_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    softwarever_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_softwarever().empty()) {
    softwarever_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_softwarever(), 
      GetArenaForAllocation());
  }
  serialnumber_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    serialnumber_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_serialnumber().empty()) {
    serialnumber_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_serialnumber(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.DeviceInfo)
}

inline void DeviceInfo::SharedCtor() {
devicever_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  devicever_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
fpgaver_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  fpgaver_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
softwarever_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  softwarever_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
serialnumber_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  serialnumber_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DeviceInfo::~DeviceInfo() {
  // @@protoc_insertion_point(destructor:IntelliSwing.DeviceInfo)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DeviceInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  devicever_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fpgaver_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  softwarever_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  serialnumber_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DeviceInfo::ArenaDtor(void* object) {
  DeviceInfo* _this = reinterpret_cast< DeviceInfo* >(object);
  (void)_this;
}
void DeviceInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DeviceInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DeviceInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.DeviceInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  devicever_.ClearToEmpty();
  fpgaver_.ClearToEmpty();
  softwarever_.ClearToEmpty();
  serialnumber_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeviceInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string deviceVer = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_devicever();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "IntelliSwing.DeviceInfo.deviceVer"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string fpgaVer = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_fpgaver();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "IntelliSwing.DeviceInfo.fpgaVer"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string softwareVer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_softwarever();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "IntelliSwing.DeviceInfo.softwareVer"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string serialNumber = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_serialnumber();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "IntelliSwing.DeviceInfo.serialNumber"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DeviceInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.DeviceInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string deviceVer = 1;
  if (!this->_internal_devicever().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_devicever().data(), static_cast<int>(this->_internal_devicever().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IntelliSwing.DeviceInfo.deviceVer");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_devicever(), target);
  }

  // string fpgaVer = 2;
  if (!this->_internal_fpgaver().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fpgaver().data(), static_cast<int>(this->_internal_fpgaver().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IntelliSwing.DeviceInfo.fpgaVer");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fpgaver(), target);
  }

  // string softwareVer = 3;
  if (!this->_internal_softwarever().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_softwarever().data(), static_cast<int>(this->_internal_softwarever().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IntelliSwing.DeviceInfo.softwareVer");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_softwarever(), target);
  }

  // string serialNumber = 4;
  if (!this->_internal_serialnumber().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_serialnumber().data(), static_cast<int>(this->_internal_serialnumber().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IntelliSwing.DeviceInfo.serialNumber");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_serialnumber(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.DeviceInfo)
  return target;
}

size_t DeviceInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.DeviceInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string deviceVer = 1;
  if (!this->_internal_devicever().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_devicever());
  }

  // string fpgaVer = 2;
  if (!this->_internal_fpgaver().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fpgaver());
  }

  // string softwareVer = 3;
  if (!this->_internal_softwarever().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_softwarever());
  }

  // string serialNumber = 4;
  if (!this->_internal_serialnumber().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_serialnumber());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeviceInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DeviceInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeviceInfo::GetClassData() const { return &_class_data_; }

void DeviceInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<DeviceInfo *>(to)->MergeFrom(
      static_cast<const DeviceInfo &>(from));
}


void DeviceInfo::MergeFrom(const DeviceInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.DeviceInfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_devicever().empty()) {
    _internal_set_devicever(from._internal_devicever());
  }
  if (!from._internal_fpgaver().empty()) {
    _internal_set_fpgaver(from._internal_fpgaver());
  }
  if (!from._internal_softwarever().empty()) {
    _internal_set_softwarever(from._internal_softwarever());
  }
  if (!from._internal_serialnumber().empty()) {
    _internal_set_serialnumber(from._internal_serialnumber());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeviceInfo::CopyFrom(const DeviceInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.DeviceInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceInfo::IsInitialized() const {
  return true;
}

void DeviceInfo::InternalSwap(DeviceInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &devicever_, lhs_arena,
      &other->devicever_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &fpgaver_, lhs_arena,
      &other->fpgaver_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &softwarever_, lhs_arena,
      &other->softwarever_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &serialnumber_, lhs_arena,
      &other->serialnumber_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata DeviceInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[0]);
}

// ===================================================================

class DiviceStatus::_Internal {
 public:
  static const ::IntelliSwing::ReturnMsg& systemstate(const DiviceStatus* msg);
};

const ::IntelliSwing::ReturnMsg&
DiviceStatus::_Internal::systemstate(const DiviceStatus* msg) {
  return *msg->systemstate_;
}
void DiviceStatus::clear_sensorstate() {
  sensorstate_.Clear();
}
void DiviceStatus::clear_systemstate() {
  if (GetArenaForAllocation() == nullptr && systemstate_ != nullptr) {
    delete systemstate_;
  }
  systemstate_ = nullptr;
}
DiviceStatus::DiviceStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  sensorstate_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.DiviceStatus)
}
DiviceStatus::DiviceStatus(const DiviceStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      sensorstate_(from.sensorstate_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_systemstate()) {
    systemstate_ = new ::IntelliSwing::ReturnMsg(*from.systemstate_);
  } else {
    systemstate_ = nullptr;
  }
  ::memcpy(&devicetemperature_, &from.devicetemperature_,
    static_cast<size_t>(reinterpret_cast<char*>(&batteryinfo_) -
    reinterpret_cast<char*>(&devicetemperature_)) + sizeof(batteryinfo_));
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.DiviceStatus)
}

inline void DiviceStatus::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&systemstate_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&batteryinfo_) -
    reinterpret_cast<char*>(&systemstate_)) + sizeof(batteryinfo_));
}

DiviceStatus::~DiviceStatus() {
  // @@protoc_insertion_point(destructor:IntelliSwing.DiviceStatus)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DiviceStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete systemstate_;
}

void DiviceStatus::ArenaDtor(void* object) {
  DiviceStatus* _this = reinterpret_cast< DiviceStatus* >(object);
  (void)_this;
}
void DiviceStatus::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DiviceStatus::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DiviceStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.DiviceStatus)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sensorstate_.Clear();
  if (GetArenaForAllocation() == nullptr && systemstate_ != nullptr) {
    delete systemstate_;
  }
  systemstate_ = nullptr;
  ::memset(&devicetemperature_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&batteryinfo_) -
      reinterpret_cast<char*>(&devicetemperature_)) + sizeof(batteryinfo_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DiviceStatus::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .IntelliSwing.ReturnMsg sensorState = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sensorstate(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .IntelliSwing.ReturnMsg systemState = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_systemstate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float deviceTemperature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          devicetemperature_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float batteryInfo = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          batteryinfo_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DiviceStatus::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.DiviceStatus)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .IntelliSwing.ReturnMsg sensorState = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sensorstate_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_sensorstate(i), target, stream);
  }

  // .IntelliSwing.ReturnMsg systemState = 2;
  if (this->_internal_has_systemstate()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::systemstate(this), target, stream);
  }

  // float deviceTemperature = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_devicetemperature = this->_internal_devicetemperature();
  uint32_t raw_devicetemperature;
  memcpy(&raw_devicetemperature, &tmp_devicetemperature, sizeof(tmp_devicetemperature));
  if (raw_devicetemperature != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_devicetemperature(), target);
  }

  // float batteryInfo = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_batteryinfo = this->_internal_batteryinfo();
  uint32_t raw_batteryinfo;
  memcpy(&raw_batteryinfo, &tmp_batteryinfo, sizeof(tmp_batteryinfo));
  if (raw_batteryinfo != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_batteryinfo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.DiviceStatus)
  return target;
}

size_t DiviceStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.DiviceStatus)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .IntelliSwing.ReturnMsg sensorState = 1;
  total_size += 1UL * this->_internal_sensorstate_size();
  for (const auto& msg : this->sensorstate_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .IntelliSwing.ReturnMsg systemState = 2;
  if (this->_internal_has_systemstate()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *systemstate_);
  }

  // float deviceTemperature = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_devicetemperature = this->_internal_devicetemperature();
  uint32_t raw_devicetemperature;
  memcpy(&raw_devicetemperature, &tmp_devicetemperature, sizeof(tmp_devicetemperature));
  if (raw_devicetemperature != 0) {
    total_size += 1 + 4;
  }

  // float batteryInfo = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_batteryinfo = this->_internal_batteryinfo();
  uint32_t raw_batteryinfo;
  memcpy(&raw_batteryinfo, &tmp_batteryinfo, sizeof(tmp_batteryinfo));
  if (raw_batteryinfo != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DiviceStatus::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DiviceStatus::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DiviceStatus::GetClassData() const { return &_class_data_; }

void DiviceStatus::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<DiviceStatus *>(to)->MergeFrom(
      static_cast<const DiviceStatus &>(from));
}


void DiviceStatus::MergeFrom(const DiviceStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.DiviceStatus)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  sensorstate_.MergeFrom(from.sensorstate_);
  if (from._internal_has_systemstate()) {
    _internal_mutable_systemstate()->::IntelliSwing::ReturnMsg::MergeFrom(from._internal_systemstate());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_devicetemperature = from._internal_devicetemperature();
  uint32_t raw_devicetemperature;
  memcpy(&raw_devicetemperature, &tmp_devicetemperature, sizeof(tmp_devicetemperature));
  if (raw_devicetemperature != 0) {
    _internal_set_devicetemperature(from._internal_devicetemperature());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_batteryinfo = from._internal_batteryinfo();
  uint32_t raw_batteryinfo;
  memcpy(&raw_batteryinfo, &tmp_batteryinfo, sizeof(tmp_batteryinfo));
  if (raw_batteryinfo != 0) {
    _internal_set_batteryinfo(from._internal_batteryinfo());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DiviceStatus::CopyFrom(const DiviceStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.DiviceStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiviceStatus::IsInitialized() const {
  return true;
}

void DiviceStatus::InternalSwap(DiviceStatus* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  sensorstate_.InternalSwap(&other->sensorstate_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DiviceStatus, batteryinfo_)
      + sizeof(DiviceStatus::batteryinfo_)
      - PROTOBUF_FIELD_OFFSET(DiviceStatus, systemstate_)>(
          reinterpret_cast<char*>(&systemstate_),
          reinterpret_cast<char*>(&other->systemstate_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DiviceStatus::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[1]);
}

// ===================================================================

class LogRequest::_Internal {
 public:
};

LogRequest::LogRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.LogRequest)
}
LogRequest::LogRequest(const LogRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&systemrange_, &from.systemrange_,
    static_cast<size_t>(reinterpret_cast<char*>(&processinglogrange_) -
    reinterpret_cast<char*>(&systemrange_)) + sizeof(processinglogrange_));
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.LogRequest)
}

inline void LogRequest::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&systemrange_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&processinglogrange_) -
    reinterpret_cast<char*>(&systemrange_)) + sizeof(processinglogrange_));
}

LogRequest::~LogRequest() {
  // @@protoc_insertion_point(destructor:IntelliSwing.LogRequest)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void LogRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LogRequest::ArenaDtor(void* object) {
  LogRequest* _this = reinterpret_cast< LogRequest* >(object);
  (void)_this;
}
void LogRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LogRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void LogRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.LogRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&systemrange_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&processinglogrange_) -
      reinterpret_cast<char*>(&systemrange_)) + sizeof(processinglogrange_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 systemRange = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          systemrange_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 processingLogrange = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          processinglogrange_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LogRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.LogRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 systemRange = 1;
  if (this->_internal_systemrange() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_systemrange(), target);
  }

  // int32 processingLogrange = 2;
  if (this->_internal_processinglogrange() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_processinglogrange(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.LogRequest)
  return target;
}

size_t LogRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.LogRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 systemRange = 1;
  if (this->_internal_systemrange() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_systemrange());
  }

  // int32 processingLogrange = 2;
  if (this->_internal_processinglogrange() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_processinglogrange());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    LogRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogRequest::GetClassData() const { return &_class_data_; }

void LogRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<LogRequest *>(to)->MergeFrom(
      static_cast<const LogRequest &>(from));
}


void LogRequest::MergeFrom(const LogRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.LogRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_systemrange() != 0) {
    _internal_set_systemrange(from._internal_systemrange());
  }
  if (from._internal_processinglogrange() != 0) {
    _internal_set_processinglogrange(from._internal_processinglogrange());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogRequest::CopyFrom(const LogRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.LogRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogRequest::IsInitialized() const {
  return true;
}

void LogRequest::InternalSwap(LogRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LogRequest, processinglogrange_)
      + sizeof(LogRequest::processinglogrange_)
      - PROTOBUF_FIELD_OFFSET(LogRequest, systemrange_)>(
          reinterpret_cast<char*>(&systemrange_),
          reinterpret_cast<char*>(&other->systemrange_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LogRequest::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[2]);
}

// ===================================================================

class LogMessage::_Internal {
 public:
};

LogMessage::LogMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  systemlog_(arena),
  processinglog_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.LogMessage)
}
LogMessage::LogMessage(const LogMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      systemlog_(from.systemlog_),
      processinglog_(from.processinglog_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.LogMessage)
}

inline void LogMessage::SharedCtor() {
}

LogMessage::~LogMessage() {
  // @@protoc_insertion_point(destructor:IntelliSwing.LogMessage)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void LogMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LogMessage::ArenaDtor(void* object) {
  LogMessage* _this = reinterpret_cast< LogMessage* >(object);
  (void)_this;
}
void LogMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LogMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void LogMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.LogMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  systemlog_.Clear();
  processinglog_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string systemLog = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_systemlog();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "IntelliSwing.LogMessage.systemLog"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string processingLog = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_processinglog();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "IntelliSwing.LogMessage.processingLog"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LogMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.LogMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string systemLog = 1;
  for (int i = 0, n = this->_internal_systemlog_size(); i < n; i++) {
    const auto& s = this->_internal_systemlog(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IntelliSwing.LogMessage.systemLog");
    target = stream->WriteString(1, s, target);
  }

  // repeated string processingLog = 2;
  for (int i = 0, n = this->_internal_processinglog_size(); i < n; i++) {
    const auto& s = this->_internal_processinglog(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "IntelliSwing.LogMessage.processingLog");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.LogMessage)
  return target;
}

size_t LogMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.LogMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string systemLog = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(systemlog_.size());
  for (int i = 0, n = systemlog_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      systemlog_.Get(i));
  }

  // repeated string processingLog = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(processinglog_.size());
  for (int i = 0, n = processinglog_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      processinglog_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    LogMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogMessage::GetClassData() const { return &_class_data_; }

void LogMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<LogMessage *>(to)->MergeFrom(
      static_cast<const LogMessage &>(from));
}


void LogMessage::MergeFrom(const LogMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.LogMessage)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  systemlog_.MergeFrom(from.systemlog_);
  processinglog_.MergeFrom(from.processinglog_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogMessage::CopyFrom(const LogMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.LogMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogMessage::IsInitialized() const {
  return true;
}

void LogMessage::InternalSwap(LogMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  systemlog_.InternalSwap(&other->systemlog_);
  processinglog_.InternalSwap(&other->processinglog_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LogMessage::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[3]);
}

// ===================================================================

class SensorStatistics::_Internal {
 public:
};

SensorStatistics::SensorStatistics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.SensorStatistics)
}
SensorStatistics::SensorStatistics(const SensorStatistics& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  shot_count_ = from.shot_count_;
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.SensorStatistics)
}

inline void SensorStatistics::SharedCtor() {
shot_count_ = 0;
}

SensorStatistics::~SensorStatistics() {
  // @@protoc_insertion_point(destructor:IntelliSwing.SensorStatistics)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SensorStatistics::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SensorStatistics::ArenaDtor(void* object) {
  SensorStatistics* _this = reinterpret_cast< SensorStatistics* >(object);
  (void)_this;
}
void SensorStatistics::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SensorStatistics::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SensorStatistics::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.SensorStatistics)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  shot_count_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SensorStatistics::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 shot_count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          shot_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SensorStatistics::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.SensorStatistics)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 shot_count = 1;
  if (this->_internal_shot_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_shot_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.SensorStatistics)
  return target;
}

size_t SensorStatistics::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.SensorStatistics)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 shot_count = 1;
  if (this->_internal_shot_count() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_shot_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SensorStatistics::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SensorStatistics::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SensorStatistics::GetClassData() const { return &_class_data_; }

void SensorStatistics::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SensorStatistics *>(to)->MergeFrom(
      static_cast<const SensorStatistics &>(from));
}


void SensorStatistics::MergeFrom(const SensorStatistics& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.SensorStatistics)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_shot_count() != 0) {
    _internal_set_shot_count(from._internal_shot_count());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SensorStatistics::CopyFrom(const SensorStatistics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.SensorStatistics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorStatistics::IsInitialized() const {
  return true;
}

void SensorStatistics::InternalSwap(SensorStatistics* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(shot_count_, other->shot_count_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SensorStatistics::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[4]);
}

// ===================================================================

class SiteCalibrationResult::_Internal {
 public:
  static const ::IntelliSwing::ReturnMsg& state(const SiteCalibrationResult* msg);
};

const ::IntelliSwing::ReturnMsg&
SiteCalibrationResult::_Internal::state(const SiteCalibrationResult* msg) {
  return *msg->state_;
}
void SiteCalibrationResult::clear_state() {
  if (GetArenaForAllocation() == nullptr && state_ != nullptr) {
    delete state_;
  }
  state_ = nullptr;
}
SiteCalibrationResult::SiteCalibrationResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.SiteCalibrationResult)
}
SiteCalibrationResult::SiteCalibrationResult(const SiteCalibrationResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_state()) {
    state_ = new ::IntelliSwing::ReturnMsg(*from.state_);
  } else {
    state_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.SiteCalibrationResult)
}

inline void SiteCalibrationResult::SharedCtor() {
state_ = nullptr;
}

SiteCalibrationResult::~SiteCalibrationResult() {
  // @@protoc_insertion_point(destructor:IntelliSwing.SiteCalibrationResult)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SiteCalibrationResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete state_;
}

void SiteCalibrationResult::ArenaDtor(void* object) {
  SiteCalibrationResult* _this = reinterpret_cast< SiteCalibrationResult* >(object);
  (void)_this;
}
void SiteCalibrationResult::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SiteCalibrationResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SiteCalibrationResult::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.SiteCalibrationResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && state_ != nullptr) {
    delete state_;
  }
  state_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SiteCalibrationResult::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .IntelliSwing.ReturnMsg state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SiteCalibrationResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.SiteCalibrationResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .IntelliSwing.ReturnMsg state = 1;
  if (this->_internal_has_state()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::state(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.SiteCalibrationResult)
  return target;
}

size_t SiteCalibrationResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.SiteCalibrationResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .IntelliSwing.ReturnMsg state = 1;
  if (this->_internal_has_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *state_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SiteCalibrationResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SiteCalibrationResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SiteCalibrationResult::GetClassData() const { return &_class_data_; }

void SiteCalibrationResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SiteCalibrationResult *>(to)->MergeFrom(
      static_cast<const SiteCalibrationResult &>(from));
}


void SiteCalibrationResult::MergeFrom(const SiteCalibrationResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.SiteCalibrationResult)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_state()) {
    _internal_mutable_state()->::IntelliSwing::ReturnMsg::MergeFrom(from._internal_state());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SiteCalibrationResult::CopyFrom(const SiteCalibrationResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.SiteCalibrationResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SiteCalibrationResult::IsInitialized() const {
  return true;
}

void SiteCalibrationResult::InternalSwap(SiteCalibrationResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(state_, other->state_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SiteCalibrationResult::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[5]);
}

// ===================================================================

class Firmware::_Internal {
 public:
};

Firmware::Firmware(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.Firmware)
}
Firmware::Firmware(const Firmware& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sensorfirmware_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    sensorfirmware_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sensorfirmware().empty()) {
    sensorfirmware_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sensorfirmware(), 
      GetArenaForAllocation());
  }
  fpgafirmware_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    fpgafirmware_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fpgafirmware().empty()) {
    fpgafirmware_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_fpgafirmware(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.Firmware)
}

inline void Firmware::SharedCtor() {
sensorfirmware_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  sensorfirmware_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
fpgafirmware_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  fpgafirmware_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Firmware::~Firmware() {
  // @@protoc_insertion_point(destructor:IntelliSwing.Firmware)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Firmware::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  sensorfirmware_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  fpgafirmware_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Firmware::ArenaDtor(void* object) {
  Firmware* _this = reinterpret_cast< Firmware* >(object);
  (void)_this;
}
void Firmware::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Firmware::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Firmware::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.Firmware)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sensorfirmware_.ClearToEmpty();
  fpgafirmware_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Firmware::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes sensorFirmware = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_sensorfirmware();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes fpgaFirmware = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_fpgafirmware();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Firmware::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.Firmware)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes sensorFirmware = 1;
  if (!this->_internal_sensorfirmware().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_sensorfirmware(), target);
  }

  // bytes fpgaFirmware = 2;
  if (!this->_internal_fpgafirmware().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_fpgafirmware(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.Firmware)
  return target;
}

size_t Firmware::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.Firmware)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes sensorFirmware = 1;
  if (!this->_internal_sensorfirmware().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_sensorfirmware());
  }

  // bytes fpgaFirmware = 2;
  if (!this->_internal_fpgafirmware().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_fpgafirmware());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Firmware::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Firmware::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Firmware::GetClassData() const { return &_class_data_; }

void Firmware::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Firmware *>(to)->MergeFrom(
      static_cast<const Firmware &>(from));
}


void Firmware::MergeFrom(const Firmware& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.Firmware)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sensorfirmware().empty()) {
    _internal_set_sensorfirmware(from._internal_sensorfirmware());
  }
  if (!from._internal_fpgafirmware().empty()) {
    _internal_set_fpgafirmware(from._internal_fpgafirmware());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Firmware::CopyFrom(const Firmware& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.Firmware)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Firmware::IsInitialized() const {
  return true;
}

void Firmware::InternalSwap(Firmware* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &sensorfirmware_, lhs_arena,
      &other->sensorfirmware_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &fpgafirmware_, lhs_arena,
      &other->fpgafirmware_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Firmware::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[6]);
}

// ===================================================================

class UpdateFirmwareResult::_Internal {
 public:
  static const ::IntelliSwing::ReturnMsg& fpgastate(const UpdateFirmwareResult* msg);
  static const ::IntelliSwing::ReturnMsg& sensorsw(const UpdateFirmwareResult* msg);
};

const ::IntelliSwing::ReturnMsg&
UpdateFirmwareResult::_Internal::fpgastate(const UpdateFirmwareResult* msg) {
  return *msg->fpgastate_;
}
const ::IntelliSwing::ReturnMsg&
UpdateFirmwareResult::_Internal::sensorsw(const UpdateFirmwareResult* msg) {
  return *msg->sensorsw_;
}
void UpdateFirmwareResult::clear_fpgastate() {
  if (GetArenaForAllocation() == nullptr && fpgastate_ != nullptr) {
    delete fpgastate_;
  }
  fpgastate_ = nullptr;
}
void UpdateFirmwareResult::clear_sensorsw() {
  if (GetArenaForAllocation() == nullptr && sensorsw_ != nullptr) {
    delete sensorsw_;
  }
  sensorsw_ = nullptr;
}
UpdateFirmwareResult::UpdateFirmwareResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:IntelliSwing.UpdateFirmwareResult)
}
UpdateFirmwareResult::UpdateFirmwareResult(const UpdateFirmwareResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_fpgastate()) {
    fpgastate_ = new ::IntelliSwing::ReturnMsg(*from.fpgastate_);
  } else {
    fpgastate_ = nullptr;
  }
  if (from._internal_has_sensorsw()) {
    sensorsw_ = new ::IntelliSwing::ReturnMsg(*from.sensorsw_);
  } else {
    sensorsw_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:IntelliSwing.UpdateFirmwareResult)
}

inline void UpdateFirmwareResult::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&fpgastate_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&sensorsw_) -
    reinterpret_cast<char*>(&fpgastate_)) + sizeof(sensorsw_));
}

UpdateFirmwareResult::~UpdateFirmwareResult() {
  // @@protoc_insertion_point(destructor:IntelliSwing.UpdateFirmwareResult)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void UpdateFirmwareResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete fpgastate_;
  if (this != internal_default_instance()) delete sensorsw_;
}

void UpdateFirmwareResult::ArenaDtor(void* object) {
  UpdateFirmwareResult* _this = reinterpret_cast< UpdateFirmwareResult* >(object);
  (void)_this;
}
void UpdateFirmwareResult::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UpdateFirmwareResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void UpdateFirmwareResult::Clear() {
// @@protoc_insertion_point(message_clear_start:IntelliSwing.UpdateFirmwareResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && fpgastate_ != nullptr) {
    delete fpgastate_;
  }
  fpgastate_ = nullptr;
  if (GetArenaForAllocation() == nullptr && sensorsw_ != nullptr) {
    delete sensorsw_;
  }
  sensorsw_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UpdateFirmwareResult::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .IntelliSwing.ReturnMsg FpgaState = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_fpgastate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .IntelliSwing.ReturnMsg SensorSW = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_sensorsw(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UpdateFirmwareResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IntelliSwing.UpdateFirmwareResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .IntelliSwing.ReturnMsg FpgaState = 1;
  if (this->_internal_has_fpgastate()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::fpgastate(this), target, stream);
  }

  // .IntelliSwing.ReturnMsg SensorSW = 2;
  if (this->_internal_has_sensorsw()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::sensorsw(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IntelliSwing.UpdateFirmwareResult)
  return target;
}

size_t UpdateFirmwareResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IntelliSwing.UpdateFirmwareResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .IntelliSwing.ReturnMsg FpgaState = 1;
  if (this->_internal_has_fpgastate()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *fpgastate_);
  }

  // .IntelliSwing.ReturnMsg SensorSW = 2;
  if (this->_internal_has_sensorsw()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *sensorsw_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UpdateFirmwareResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    UpdateFirmwareResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UpdateFirmwareResult::GetClassData() const { return &_class_data_; }

void UpdateFirmwareResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<UpdateFirmwareResult *>(to)->MergeFrom(
      static_cast<const UpdateFirmwareResult &>(from));
}


void UpdateFirmwareResult::MergeFrom(const UpdateFirmwareResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IntelliSwing.UpdateFirmwareResult)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_fpgastate()) {
    _internal_mutable_fpgastate()->::IntelliSwing::ReturnMsg::MergeFrom(from._internal_fpgastate());
  }
  if (from._internal_has_sensorsw()) {
    _internal_mutable_sensorsw()->::IntelliSwing::ReturnMsg::MergeFrom(from._internal_sensorsw());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateFirmwareResult::CopyFrom(const UpdateFirmwareResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IntelliSwing.UpdateFirmwareResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateFirmwareResult::IsInitialized() const {
  return true;
}

void UpdateFirmwareResult::InternalSwap(UpdateFirmwareResult* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateFirmwareResult, sensorsw_)
      + sizeof(UpdateFirmwareResult::sensorsw_)
      - PROTOBUF_FIELD_OFFSET(UpdateFirmwareResult, fpgastate_)>(
          reinterpret_cast<char*>(&fpgastate_),
          reinterpret_cast<char*>(&other->fpgastate_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UpdateFirmwareResult::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_IntelliSwingService_2eproto_getter, &descriptor_table_IntelliSwingService_2eproto_once,
      file_level_metadata_IntelliSwingService_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace IntelliSwing
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::IntelliSwing::DeviceInfo* Arena::CreateMaybeMessage< ::IntelliSwing::DeviceInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::DeviceInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::DiviceStatus* Arena::CreateMaybeMessage< ::IntelliSwing::DiviceStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::DiviceStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::LogRequest* Arena::CreateMaybeMessage< ::IntelliSwing::LogRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::LogRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::LogMessage* Arena::CreateMaybeMessage< ::IntelliSwing::LogMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::LogMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::SensorStatistics* Arena::CreateMaybeMessage< ::IntelliSwing::SensorStatistics >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::SensorStatistics >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::SiteCalibrationResult* Arena::CreateMaybeMessage< ::IntelliSwing::SiteCalibrationResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::SiteCalibrationResult >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::Firmware* Arena::CreateMaybeMessage< ::IntelliSwing::Firmware >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::Firmware >(arena);
}
template<> PROTOBUF_NOINLINE ::IntelliSwing::UpdateFirmwareResult* Arena::CreateMaybeMessage< ::IntelliSwing::UpdateFirmwareResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::IntelliSwing::UpdateFirmwareResult >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
