# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntype.proto\x12\x0cIntelliSwing\"\x1f\n\x07Point2i\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1f\n\x07Point2f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"*\n\x07Point3i\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"*\n\x07Point3f\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"?\n\tReturnMsg\x12\x0c\n\x04isOK\x18\x01 \x01(\x08\x12\x11\n\terrorCode\x18\x02 \x01(\x05\x12\x11\n\terrorDesc\x18\x03 \x01(\tb\x06proto3')



_POINT2I = DESCRIPTOR.message_types_by_name['Point2i']
_POINT2F = DESCRIPTOR.message_types_by_name['Point2f']
_POINT3I = DESCRIPTOR.message_types_by_name['Point3i']
_POINT3F = DESCRIPTOR.message_types_by_name['Point3f']
_RETURNMSG = DESCRIPTOR.message_types_by_name['ReturnMsg']
Point2i = _reflection.GeneratedProtocolMessageType('Point2i', (_message.Message,), {
  'DESCRIPTOR' : _POINT2I,
  '__module__' : 'type_pb2'
  # @@protoc_insertion_point(class_scope:IntelliSwing.Point2i)
  })
_sym_db.RegisterMessage(Point2i)

Point2f = _reflection.GeneratedProtocolMessageType('Point2f', (_message.Message,), {
  'DESCRIPTOR' : _POINT2F,
  '__module__' : 'type_pb2'
  # @@protoc_insertion_point(class_scope:IntelliSwing.Point2f)
  })
_sym_db.RegisterMessage(Point2f)

Point3i = _reflection.GeneratedProtocolMessageType('Point3i', (_message.Message,), {
  'DESCRIPTOR' : _POINT3I,
  '__module__' : 'type_pb2'
  # @@protoc_insertion_point(class_scope:IntelliSwing.Point3i)
  })
_sym_db.RegisterMessage(Point3i)

Point3f = _reflection.GeneratedProtocolMessageType('Point3f', (_message.Message,), {
  'DESCRIPTOR' : _POINT3F,
  '__module__' : 'type_pb2'
  # @@protoc_insertion_point(class_scope:IntelliSwing.Point3f)
  })
_sym_db.RegisterMessage(Point3f)

ReturnMsg = _reflection.GeneratedProtocolMessageType('ReturnMsg', (_message.Message,), {
  'DESCRIPTOR' : _RETURNMSG,
  '__module__' : 'type_pb2'
  # @@protoc_insertion_point(class_scope:IntelliSwing.ReturnMsg)
  })
_sym_db.RegisterMessage(ReturnMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT2I._serialized_start=28
  _POINT2I._serialized_end=59
  _POINT2F._serialized_start=61
  _POINT2F._serialized_end=92
  _POINT3I._serialized_start=94
  _POINT3I._serialized_end=136
  _POINT3F._serialized_start=138
  _POINT3F._serialized_end=180
  _RETURNMSG._serialized_start=182
  _RETURNMSG._serialized_end=245
# @@protoc_insertion_point(module_scope)
